### ISSUE TITLE
Element 'bookmarks': This element is not expected.

### ISSUE THREAD

**Issue by joeybab3** [goivvy/admin-grid-tutorial#1]
Running the module and installing gave me this error when I visit the Category listing page:
```
Element 'bookmarks': This element is not expected. Expected is one of ( settings, action, actionDelete, actions, actionsColumn, bookmark, boolean, button, checkbox, checkboxset ).
Line: 37
```

Changing that line from 'bookmarks' to 'bookmark' reveals a new error:
```
1 exception(s):
Exception #0 (ReflectionException): Class Dev\Grid\Ui\Component\Category\Listing\Bookmark does not exist
```

Indeed there is no file following that convention. Any idea where I might find that file or if it's ok to just remove the bookmark section?

**Comment by joeybab3** [comment]
For the record, I'm on Magento ver. 2.3.5.

**Comment by joeybab3** [comment]
Seems the line 

`<bookmark name="bookmarks" class="Magento\Ui\Component\Category\Listing\Bookmark"/>`

Works when it is simplified to this:

`<bookmark name="bookmarks"/>`

But then the page just loads the skeleton and the content loads indefinitely.

![Screen Shot 2020-07-14 at 3 50 43 PM](https://user-images.githubusercontent.com/2829457/87483922-cc11ec80-c5e9-11ea-9cb6-23f8587b28ed.png)

**Comment by goivvy** [comment]
@joeybab3 Thanks. Let me setup 2.3.5 and test, will report back.

**Comment by goivvy** [comment]
I couldn't replicate the issue on 2.3.5-p1 in production mode.
What would happen if you replace that line with:

<bookmark name="bookmarks"/>

?

**Comment by joeybab3** [comment]
Here is the full error in 2.3.5 with a fresh copy off your repo:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/srv/public_html/app/code/Dev/Grid/view/adminhtml/ui_component/dev_grid_category_listing.xml" is invalid:
Element 'bookmarks': This element is not expected. Expected is one of ( settings, action, actionDelete, actions, actionsColumn, bookmark, boolean, button, checkbox, checkboxset ).
Line: 37

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/srv/public_html/app/code/Dev/Grid/view/adminhtml/ui_component/dev_grid_category_listing.xml" is invalid:
Element 'bookmarks': This element is not expected. Expected is one of ( settings, action, actionDelete, actions, actionsColumn, bookmark, boolean, button, checkbox, checkboxset ).
Line: 37

Verify the XML and try again.
<pre>#1 Magento\Ui\Config\Reader->read() called at [vendor/magento/module-ui/Config/Data.php:102]
#2 Magento\Ui\Config\Data->initData() called at [vendor/magento/module-ui/Config/Data.php:136]
#3 Magento\Ui\Config\Data->get() called at [vendor/magento/framework/View/Layout/Reader/UiComponent.php:100]
#4 Magento\Framework\View\Layout\Reader\UiComponent->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#5 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout/Reader/Container.php:84]
#6 Magento\Framework\View\Layout\Reader\Container->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#7 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Page/Config/Reader/Body.php:68]
#8 Magento\Framework\View\Page\Config\Reader\Body->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#9 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout.php:334]
#10 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#11 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#12 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#13 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#14 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:259]
#15 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:884]
#16 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#17 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#18 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#19 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() called at [app/code/Dev/Grid/Controller/Adminhtml/Index/Index.php:25]
#20 Dev\Grid\Controller\Adminhtml\Index\Index->execute() called at [generated/code/Dev/Grid/Controller/Adminhtml/Index/Index/Interceptor.php:24]
#21 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#22 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#23 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#24 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#25 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#26 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#27 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#28 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() called at [generated/code/Dev/Grid/Controller/Adminhtml/Index/Index/Interceptor.php:39]
#29 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:162]
#30 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:98]
#31 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#32 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#33 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#35 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#36 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#37 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#38 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by joeybab3** [comment]
Changing the line from 
`<bookmarks name="bookmarks" class="Dev\Grid\Ui\Component\Category\Listing\Bookmark"/>`

to

`<bookmark name="bookmarks" class="Dev\Grid\Ui\Component\Category\Listing\Bookmark"/>`

Fixes the previous error and causes the next one:

1 exception(s):
Exception #0 (ReflectionException): Class Dev\Grid\Ui\Component\Category\Listing\Bookmark does not exist

Exception #0 (ReflectionException): Class Dev\Grid\Ui\Component\Category\Listing\Bookmark does not exist
<pre>#1 Magento\Framework\Code\Reader\ClassReader->getConstructor() called at [vendor/magento/framework/ObjectManager/Definition/Runtime.php:54]
#2 Magento\Framework\ObjectManager\Definition\Runtime->getParameters() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:164]
#5 Magento\Framework\View\Element\UiComponentFactory->createChildComponent() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:142]
#6 Magento\Framework\View\Element\UiComponentFactory->createChildComponent() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:235]
#7 Magento\Framework\View\Element\UiComponentFactory->create() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:140]
#8 Magento\Framework\View\Layout\Generator\UiComponent->generateComponent() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:103]
#9 Magento\Framework\View\Layout\Generator\UiComponent->process() called at [vendor/magento/framework/View/Layout/GeneratorPool.php:81]
#10 Magento\Framework\View\Layout\GeneratorPool->process() called at [vendor/magento/framework/View/Layout.php:352]
#11 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#12 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#13 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#14 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#15 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:259]
#16 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:884]
#17 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#18 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#19 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#20 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() called at [app/code/Dev/Grid/Controller/Adminhtml/Index/Index.php:25]
#21 Dev\Grid\Controller\Adminhtml\Index\Index->execute() called at [generated/code/Dev/Grid/Controller/Adminhtml/Index/Index/Interceptor.php:24]
#22 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#23 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#24 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#27 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() called at [generated/code/Dev/Grid/Controller/Adminhtml/Index/Index/Interceptor.php:39]
#30 Dev\Grid\Controller\Adminhtml\Index\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:162]
#31 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:98]
#32 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#33 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#34 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#36 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#37 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#38 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#39 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by joeybab3** [comment]
Changing the line once further to
`<bookmark name="bookmarks"/>`

Allows the page to load, but the content never shows up

**Comment by goivvy** [comment]
Pushed a fix.

Please see if the issue is resolved now.

**Comment by joeybab3** [comment]
This fixes the issue, thanks!
